configurations:
  - sources:
      include:
        - Sources/
      exclude:
        - Sources/SparkInternalTesting/
        - Sources/SparkInternalSnapshotTesting/
    templates:
      - .sourcery/template/SparkAutoMockable.stencil
    output: Sources/SparkInternalTesting/Generated/AutoMockable.generated.swift
    args:
      autoMockableImports: [Combine]
      autoMockableTestableImports: [SparkInternal]
  - sources:
      include:
        - Sources/
      exclude:
        - Sources/SparkInternalTesting/
        - Sources/SparkInternalSnapshotTesting/
    templates:
      - .sourcery/template/SparkAutoMockTest.stencil
    output: Sources/SparkInternalTesting/Generated/AutoMockTest.generated.swift
    args:
      autoMockableImports: [Combine]
      autoMockableTestableImports: [SparkInternal]
  - sources:
      include:
        - Sources/
      exclude:
        - Sources/SparkInternalTesting/
        - Sources/SparkInternalSnapshotTesting/
    templates:
      - .sourcery/template/SparkAutoPublisherTest.stencil
    output: Sources/SparkInternalTesting/Generated/AutoPublisherTest.generated.swift
    args:
      autoMockableImports: [Combine]
      autoMockableTestableImports: [SparkInternal]
  - sources:
      include:
        - Sources/
      exclude:
        - Sources/SparkInternalTesting/
        - Sources/SparkInternalSnapshotTesting/
    templates:
      - .sourcery/template/SparkAutoViewModelStub.stencil
    output: Sources/SparkInternalTesting/Generated/AutoViewModelStub.generated.swift
    args:
      autoMockableImports: [Combine]
      autoMockableTestableImports: [SparkInternal]
